Internal/yggdrasil: Added unit test
jakub-dzon/k4e-operator pull request #31
Opened 2021-10-28 09:03 UTC by eloycoto

Added unit test regarding internal/yggdrasil

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

2021-11-02 08:29 UTC, pkliczewski approved these changes

2021-11-02 09:02 UTC, jakub-dzon requested changes
Bunch of nitpicks:)

2021-11-03 07:27 UTC, jakub-dzon approved these changes

2021-11-03 07:35 UTC, masayag approved these changes

2021-11-03 07:35 UTC, merged